listen_on = "127.0.0.1"
serve_root = "./public"
error_directory = "/var/www/html/errors"
watch_dirs = [
    "/var/www/html",
]

[routing]
default_behavior = "Fetch"
extension_behaviors = [
    [ ".html", "Fetch" ],
    [ ".temp", "Fetch" ],
]
