listen_on = "127.0.0.1"
serve_root = "/var/www/html"
watch_dirs = [
    "/var/www/html",
]
default_behavior = "Deny"
extension_behaviors = [
    [ ".html", "Fetch" ],
    [ ".temp", "FetchAndProcessTemplate" ],
]